export const Strings = {
  add: "Add",
  addYourTaskCorrectionRequest: "Add Your Task Correction Request",
  adminGroup: "Admin Group",
  allPastAttendance: "All past attendance",
  addHoliday: "Add Holiday",
  approve: "Approve",
  addCheckList: "Add Check List",
  actualPresentDays: "Actual Present Days",
  addNewTask: "Add New Task",
  all: "All",
  allOnline: "All Online",
  banking:"Banking",
  hospitality:"Hospitality",
  days: "Days",
  userWithEmailAlreadyExists:"User With Email already exists",
  supplyChain:"Supply Chain",
  logistics:"Logistics",
  healthCare:"Health Care",
  education:"Education",
  retail:"Retail",
  sports:"Sports",
  oilAndNaturalGas:"Oil And Natural Gas",
  lawEnforcement:"Law Enforcement",
  realEstate:"Real Estate",
  travelTourism:"Travel & Tourism",
  health:"Health",
  finance:"Finance",
  funeral:"Funeral",
  interiorDesign:"Interior Design",
  manufacturer:"Manufacturer",
  agriculture:"Agriculture",
  employeeManagement:"Employee Management",
  attorney:"Attorney",
  onlineMarketing:"Online Marketing",
  fashion:"Fashion",
  entertainment:"Entertainment",
  ngo:"NGO",
  defense:"Defense",
  absent: "Absent",
  endTime: "End Time",
  checkList: "CheckList",
  allRoles: "allRoles",
  prev: "Prev",
  career: 'Career',
  next: "Next",
  activeList: 'active',
  improve: "Improve",
  total: "Total",
  personDetails: "Person Details",
  quickActions: "Quick Actions",
  billable: 'Is Billable',
  totalMinutes: "Total Minutes",
 updateHoliday: "Update Holiday",
 toGoal: " To Goal",
 getRewardedForReferral: 'Get Rewarded for Referral',
  isBillable:'Is Billable',
  editHoliday: "Edit Holiday",
  selectRole: "Select Role",
  time: "Time",
  agreemTechnologies: 'Agreemtech',
  approvedDate: "Approved Date",
  selectBillable: "Select Billable",
  credentialsList: "Credentials List",
  newCredential: 'Add New Credential',
  selectIsParent: "Select Is Parent",
  approvedBy: "Approved By",
  addNewLeave: 'Add New Leave',
  newTaskEntry: 'New Task Entry',
  addTask: 'Add Task',
  addCorrection: 'Add Correction',
  holidayList: "Holiday List",
  about: 'About',
  addByDetails: "Added By Details",
  addTarget: "Add Target",
  holiday: "Holidays List",
  holidayPathKey: "holiday",
  account: 'Account',
  dashboard:'Dashboard',
  performance:'Performance',
  estimatedTime: "Estimated Time (Minutes)",
  estimatedTimeInHours: "Estimated Time",
  projectsTeam:'Project Team',
  selectTask: 'Select Task',
  enter: "Enter ",
  readyToWork: "Ready to Work",
  accessability: 'Accessability',
  statusKey: "status",
  projectDetailsNotFound: "Project Details Not Found",
  apply: 'Apply',
  light: "light",
  createInvoice: "Create Invoice",
  budgetSpent: "Budget Spent",
  upcomingBirthday : 'Upcoming Birthdays',
  lastOffline: "Last Offline",
  upcomingWorkAnniversary : 'Upcoming Work Anniversary',
  todayOnLeave:'Today On Leave',
  attendenceInformation: 'Attendence Information',
  addProject: 'Add New Project',
  portfolio: 'Portfolio',
  archiveProjects:'Archived Projects',
  portfolioListing:'Portfolio Listing',
  assignedTo: 'Assigned to',
  clientDetailsNotFound: "Client Details Not Found",
  credentialDetailsNotFound: "Credential Details Not Found",
  credentials:"Credentials",
  addCredentials: "Add Credentials",
  credentialDetail : "Enter Credential Detail",
  editDetails: "Edit Detail",
  attachment: 'Attachment',
  details: "Details",
  inHouse: "In House",
  tasks: "Tasks",
  lastupdated : "Last Updated",
  estimationHours: 'Estimation Hours',
  count: "Count",
  day: "Day",
  users: "Users",
  files: "Files",
  activity: "Activity",
  privateDetails: "Private Details",
  forgotPassword: 'Forgot Password ?',
  createdBy: "Created By",
  deadlineAndReminder: "Deadline/Reminder",
  client: 'Client',
  clientListing: 'Client Listing',
  clientType: "Client Type",
  billingType: "Billing Type",
  clientView: "Client View",
  credentialView: "Credentials View",
  chooseFile: 'Choose File',
  taskCorrectionIsApprovedSuccessfully: "Task correction is approved successfully.",
  taskCorrectionIsRejectedSuccessfully: "Task correction is rejected successfully.",
  pleaseWait: 'Please wait...',
  comingSoon: "Coming Soon",
  hours: "Hours",
  cancelled: "Cancelled",
  selectClientType: "Select Client Type",
  email: 'Email',
  code: 'Code',
  forDate: 'For Date',
  from: 'From',
  dueDate: "Due Date",
  isTaskBillable: 'Is Task Billable ?',
  password: 'Password',
  comment: 'Comment',
  purchase: 'purchase',
  dark: 'Dark',
  monthlyAnalysis: "Monthly Analysis",
  selectDate: 'Select Date',
  selectPosition: "Select Position",
  selectAccount: "Select Account",
  addedDate: 'Added Date',
  goToPolicyPage: 'Go to policy page',
  notes: 'Notes',
  generalInformation: 'General Information',
  taskCorrectionStatusSuccessfullyUpdated: "Task correction status successfully updated",
  generalDetails: "General Details",
  openTask: "Open task",
  editProfile: 'Edit Profile',
  managementPortal: 'Management portal',
  home: 'Home',
  billing:'Billing Hours',
  myBillableWork:'My Billable Work',
  billableWork:"Billable Work",
  emojiNotAllowed: 'Emoji not allowed',
  leadStatusType: 'Lead Status Type',
  leadStatusUpdateComment: 'Lead Status Update Comments',
  date: 'Date',
  updateClient: 'Update Client',
  updateIpAddress: 'Update IP Address',
  ipAddressNotFound: 'IP address not found',
  ipAddressListing: 'IP Address Listing',
  good: "Good",
  pleaseEnterCountry: 'Please enter country',
  totalProductiveHoursThisMonth: "Total Productive Hours this month",
  pleaseEnterValidContactURL: 'Please enter valid contact url',
  pleaseSelectAddDate: 'Please select add date',
  oops: 'Oops!',
  billableHours:'Billable Hours',
  unbillableHours :'Unbillable Hours',
  lastMonthProductiveness:"Last month's productiveness",
  allPastLeaveTypes:'All past Leave types',
  productiveness:'Productiveness',
  leadInformation: 'Lead Information',
  searchClient: 'Search Client',
  newTicket: "New Ticket",
  externalLinks: 'External Links',
  halfDays: 'Half days',
  knowledgeBase: "KnowledgeBase",
  newCustomer: "New Customer",
  newGroup: "New Group",
  addClient: 'Add Client',
  // editTaskEntry: 'Edit Task Entry',
  addTaskEntry: 'Add Task Entry',
  previousDayTaskEntry: "Previous Day Task Entry",
  nextDayTaskEntry: "Next Day Task Entry",
  taskCorrectionRequestList: 'Task Correction Request List',
  taskCorrection: 'Tasks Correction',
  projectManagementwebsite: 'Project Management Website',
  hideTaskEntry: "Hide Task Entry",
  earlyLeave: 'Early Leave',
  searchLead: 'Search Lead',
  leadTitle: 'Title',
  confirmed: 'Confirmed',
  createPayment: "Create Payment",
  generateBill: "Generate Bill",
  subscription: "Subscription",
  biling: "Biling",
  lateEntry: "Late Entry",
  recuring: 'Recuring',
  blocked: 'Blocked',
  logoName: "Logo / Name",
  selectTaskStage: "Select Task Stage",
  firstContactSource: 'First Contact Source',
  fullPresentDays: "Full Present Days",
  totalPayableDays: "Total Payable Days",
  httpError401UnauthorizedAccess: 'HTTP Error 401:Unauthorized access',
  linkedinUrlShouldBeValid: 'Please enter valid linkedin url',
  pleaseEnterValidSlackUserName: 'Please enter valid slack user name',
  leadDescription: 'Description',
  leadRegularContactSource: 'Regular Contact Source',
  givenPrice: 'Given Price',
  refreshNow: "Refresh Now",
  clients: 'Clients',
  generateReport: 'Generate Report',
  ipAddress: 'IP Address',
  addIpAddress: 'Add IP Address',
  selectParentTask: "Select Parent Task",
  editClients: 'Edit Client',
  editTask: 'Edit Task',
  leadType: 'Lead Type',
  freelancer: 'Freelancer',
  editProject: 'Edit Project',
  selectBillingType: 'Select Billing Type',
  taskCorrectionSuccessfullyUpdated: "Task Correction Successfully Updated",
  fullDayMinutesMaxThreeDigit: 'Full day minutes should be maximum 3 digits',
  halfDayMinutesMaxThreeDigit: 'Half day minutes should be maximum 3 digits',
  earlyDayMinutesMaxThreeDigit: 'Early day minutes should be maximum 3 digits',
  company: 'Company',
  totalHours: 'Total Hours',
  imageSizeLessThanFiveHundreadKb: "Image size less than 500 kb",
  esimationHours: "Esimation Hours",
  projectManager: 'Project Manager',
  team: 'Team',
  progressStatus: 'Progress Status',
  type: 'Type',
  startDate: 'Start Date',
  endDate: 'End Date',
  actualPrice: 'Actual Price',
  reason: 'Reason',
  contactUrl: 'Contact URL',
  gj: 'GJ',
  selectLeadStatus: 'Select lead status',
  myAttendance: "My Attendance",
  masterAttendance: "Master Attendance",
  adminCalendar:"Admin Calendar",
  selectAddedBy: 'Select addedBy',
  gujarat: 'Gujarat',
  startTime: "Start Time",
  no: "No",
  todayTimeTracking: "Today's Time tracking",
  leadContactEmail: 'Contact Email',
  contactInformation: 'Contact Information',
  trackedTime: "Tracked Time",
  fullDay: "Full Day",
  halfDay: "Half Day",
  earlyDay: "Early Day",
  currentPassword: 'Current Password',
  addedBy: 'Added By',
  inActive: 'In Active',
  personalDetails: 'Personal Details',
  emailAlreadyExists: 'Email already exists',
  bonusReleaseTime: 'Bonus Release Time',
  afterCompleting3Months: 'After completing 3 Months',
  viewPolicy:'View Policy',
  currentOpenings: 'Current Openings',
  myProfile: 'My Profile',
  color: 'Color picker',
  companyName: 'Company Name',
  codeShouldBeMaxFiveChar: 'Code should be maximum letters',
  signOut: 'Sign Out',
  memberGroup: "Member Group",
  newContact: "New Contact",
  country: 'Country',
  demoSiteURL: 'Demo Site URL',
  lastUpdatedBy: "Last Updated By",
  demoSiteCredentials: 'Demo Site Credentials',
  staffGroup: 'Staff group',
  changePassword: 'Change Password',
  selectAll: 'Select All',
  website: 'Website URL',
  newPassword: 'New Password',
  phone: 'Phone',
  ftpDetails: 'FTP Details',
  mobile: 'Mobile',
  skypeId: 'Skype Id',
  leadAddedSuccessfully: 'New lead added successfully',
  credentialAddedSuccessfully:'New credentials added successfully',
  credentialEditedSuccessfully:'Credentials updated successfully',
  holidayEditedSuccessfully:'Holiday updated successfully',
  holidayAddedSuccessfully:'Holiday added successfully',
  userAddedSuccessfully: 'New user added successfully',
  userUpdatedSuccessfully: 'User updated successfully',
  payments: "Payments",
  holidayDate: "Holiday Date",
  clientAddSuccessfully: 'New client added successfully',
  clientUpdateSuccessfully: 'Client updated successfully',
  ipAddressAddSuccessfully: 'New ip address added successfully',
  ipAddressUpdateSuccessfully: 'Ip address updated successfully',
  ipAlreadyExits: 'Ip address already exists',
  projectAddSuccessfully: 'New project added successfully',
  projectUpdateSuccessfully: 'Project updated successfully',
  permission: 'Permissions',
  taskStage: "Task Stage",
  leadUpdatedSuccessfully: 'Lead updated successfully',
  taskAddedSuccessfully: 'New task added successfully',
  taskUpdatedSuccessfully: 'Task updated successfully',
  linkedinURL: 'Linkedin URL',
  searchIPaddress: 'Search IP Address',
  searchProject: 'Search Project',
  leadStatus: 'Lead Status',
  passwordUpdatedSuccessfully: 'Password updated successfully',
  resetPassword: 'Reset Password',
  cancel: 'Cancel',
  confirmPassword: 'Confirm Password',
  editIpAddress: 'Edit Ip address',
  recentTask:'Recent Tasks',
  youHavePendingPolicyToRead: 'You have pending policy to read',
  weCantFindThatPage: "We can't find that page.",
  projectStatus: "Project Status",
  returnHome: 'Return Home',
  aadharCardMustBeTwelveDigit: 'Aadhaar card must be 12 digit',
  guardianContactNumberAtLeastBeTenDigit: 'Guardian contact number at least 10 digit',
  guardianContactNumberMustBeTwelveDigit: 'Guardian contact number must be 12 digit',
  firstNameShouldBeMinThreeChar: 'please enter minimum 3 letters',
  firstNameShouldBeMaxTwentyChar: 'First name should be max 20 letters',
  lastNameShouldBeMinThreeChar: 'please enter minimum 3 letters',
  lastNameShouldBeMaxTwentyChar: 'Last name  should be max 20 letters',
  lateEntryTime: 'Late entry time',
  earlyDayMinutes: 'Early day minutes',
  halfDayMinutes: 'Half day minutes',
  fullDayMinutes: 'Full day minutes',
  guardianNameShouldBeMaxTwentyChar: 'Guardian should be max 20 letters',
  permissionShouldBeMaxTwentyChar: 'Permission name should be max 20 letters',
  roleShouldBeMaxTwentyChar: 'Role name should be max 10 letters',
  contactNumberMustBeTwelveDigit: 'Contact number must be 12 digit',
  mobileNumberMustBeTwelveDigit: 'mobile number must be 12 digit',
  alternateMobileMustBeTwelveDigit: 'Alternate mobile must be 12 digit',
  mobileNumberAtLeastTenDigit: 'Mobile number must be at least 10 digit',
  contactNumberAtLeastTenDigit: 'Contact number must be at least 10 digit',
  alternateMobileAtLeastTenDigit: 'Alternate mobile must be at least 10 digit',
  selectDefaultRole: 'Select default role',
  slackUrlShouldBeValid: 'Please enter valid slack url',
  pleaseSelectClientType: "Please select a client type",
  pleaseSelectBillingType: "Please select a billing type",
  pleaseEnterValidPanNumber: "Please enter valid pan number",
  pleaseSelectAccount: "Please select account",
  pleaseSelectPosition: "Please select position",
  lastUpdateDate: "Last Updated Date",
  pleaseEnterIpAddress: "Please enter ip address",
  pleaseEnterShortName: "Please enter short name",
  clientStatus: "Client Status",
  submit: "Submit",
  slackUserNameShouldContainDot: "Slack user name should contain dot",
  policyHistory: 'Policy history',
  nextIncrementDate: 'Next increment date',
  imageSizeError: 'Please select image size less than 2MB',
  pleaseSelectAssignPermissions: 'Please select assign permissions',
  permissionNameShouldContainDot: 'Permission name should contain dot',
  label: 'Label',
  pleaseSelectRole: 'Please select role',
  roleExists: 'Role exists',
  ipNameAlreadyExists: "IP name already exists",
  userConsentUpdatedSuccessfully: 'User consent updated successfully',
  iAcceptConsent: 'I accept consent',
  pleaseEnterLabel: 'Please enter label',
  isThisDefaultRole: 'Is this default role',
  pleaseEnterEmail: 'Please enter email',
  back: 'Back',
  permissionIsSuccessfullyUpdate: 'Permission updated successfully.',
  pleaseSelectPolicyRole: 'Please select policy role',
  policyRole: 'Policy role',
  pleaseSelectAtLeaseOnePolicyRole: 'Please select at least one policy role',
  pleaseSelectAtLeaseOnePermissionRole: 'Please select at least one permission',
  pleaseSelectNextIncrementDate: 'Please select next increment date',
  websiteUrlShouldBeValid: 'Please enter valid website url',
  pleaseSelectDefaultRole: 'Please select default role',
  pleaseSelectTask: "Please select task",
  pleaseSelectEndTime: 'Please select end time',
  pleaseSelectStartTime: 'Please select start time',
  mobileNumberShouldBeNumber: 'Mobile number Should be number',
  postalNumberShouldBeNumber: 'Postal code should ne number',
  aadharCardShouldBeNumber: 'Aadhar card should be number',
  pleaseEnterFullDayMinutes: 'Please enter full day minutes',
  pleaseSelectModule: 'Please select module',
  pleaseEnterHalfDayMinutes: 'Please enter half day minutes',
  pleaseEnterEarlyDayMinutes: 'Please enter early day minutes',
  pleaseSelectLateEntryTime: 'Please select late entry time',
  fullDayMinutesShouldBeNumber: 'Full day minutes should be number',
  halfDayMinutesShouldBeNumber: 'Half day minutes should be number',
  moduleIsRequired: 'Module is required',
  earlyDayMinutesShouldBeNumber: 'Early day minutes should be number',
  postalCodeMustBeSixDigit: 'Postal code must be 6 digit',
  guardianContactNumberShouldBeNumber: 'Guardian contact number should be number',
  pleaseEnterCompanyName: 'Please enter company name',
  pleaseEnterWebsiteUrl: 'Please enter website URL',
  projects: 'Projects',
  priority: 'Priority',
  pleaseSelectClient: 'Please select client',
  pleaseEnterTotalHours: 'Please enter total hours',
  pleaseSelectTeam: 'Please select team',
  pleaseSelectType: 'Please select type',
  pleaseSelectStartDate: 'Please select start date',
  pleaseEnterContactUrl: 'Please enter contact url',
  pleaseSelectEndDate: 'Please select end date',
  pleaseSelectProjectStatus: 'Please select project status',
  pleaseSelectProjectManager: 'Please select project manager',
  projectDetails: 'Project Details',
  pleaseEnterLinkedinUrl: 'Please enter linkedin URL',
  pleaseEnterSkypeId: 'Please enter skype ID',
  pleaseSelectProject: 'Please select project',
  pleaseSelectTools: 'Please select tools',
  salaryShouldBeNumber: 'Salary should be number',
  alternateMobileNumberShouldBeNumber: 'Alternate mobile number should be number',
  phoneShouldBeNumber: 'Phone should be number',
  permissionsNameShouldNotContainSpace: 'Permission name should not contain space',
  phoneShouldBeTwelveDigit: 'Phone should be 12 digit',
  phoneShouldBeTenDigit: 'Phone should be 10 digit',
  yes: 'Yes',
  status: 'Status',
  pleaseEnterAddedBy: 'Please enter added by',
  pleaseEnterFirstContactSource: 'Please enter first contact source',
  pleaseEnterCode: 'Please enter code',
  codeShouldBeMinThreeChar: 'Code should be minimum 3 letters',
  pleaseEnterComments: 'Please enter comments',
  demoSiteShouldBeValid: 'Please enter valid demo site url',
  liveSiteUrlShouldBeValid: 'Please enter valid live site url',
  pleaseSelectLeadType: 'Please select lead type',
  pleaseEnterLeadTitle: 'Please enter title',
  officeMaxValidTime: 'Office max valid time',
  pleaseSelectLogoSizeLessThanTwoMB: 'Please select logo size less than 2MB',
  showInPortfolio: 'Show in portfolio',
  parentTaskId: 'Parent task id',
  pleaseEnterLeadDescription: 'Please enter description',
  pleaseEnterLeadRegularContactSource: 'Please enter regular contact source',
  pleaseEnterGivenPrice: 'Please enter given price',
  givenPriceShouldBeNumber: 'Given price should be number',
  thisPermissionNameAlreadyUse: 'This permission name already exists',
  salary: 'Salary',
  selectStatus: 'Select status',
  active: 'Active',
  leaveAdjustmentDays:'Leave Adjustment Days',
  pleaseEntervalidateIpAddress: "Please enter valid ip address",
  shortNameSholdBeThreeCharacter: "Shortname should be three character",
  pleaseEnterValidJoiningDate: "Please enter valid joining date",
  pleaseSelectModeOfContact: "Please select mode of contact",
  position: "Position",
  warningMessage:"Estimation Time Must be Greater Then 1",
  pleaseSelectTaskStage: "Please select task stage",
  shortName: "Short Name",
  leaveCalender: "Leave Calender",
  statements: 'Statements',
  pleaseSelectAddedDate: "Please select added date",
  manageIp: "Manage IP",
  statusActive:'Active',
  selectUser: 'Select  User',
  selectClient: 'Select Client',
  terms: 'Terms',
  userAttendanceList: 'User Attendance List',
  modeOfContact: "Mode Of Contact",
  ourService: 'Our Service',
  knowUs: 'Know Us',
  plans: 'Plans',
  optional: '',
  pending: 'Pending',
  block: 'Block',
  permissionExists: 'Permission exists',
  pleaseSelectLeadStatus: 'Please select lead status',
  PanCardNumberMustBeCapitalLetterOrNumbers: 'Pan Card number must be capital letter and numbers',
  policyISuccessfullyUpdate: 'Policy updated successfully ',
  noMoreItem: 'No more item',
  roleIsAddSuccessfully: 'Role added successfully.',
  roleUpdateSuccessfully: 'Role updated successfully.',
  permissionAddedSuccessfully: 'Permission added successfully.',
  policyAddedSuccessfully: 'Policy added successfully.',
  contactUs: 'Contact Us',
  assignPermissions: 'Assign Permissions',
  signIn: 'Sign In',
  taskCorrectionSuccessfullyAdded: "Task Correction Successfully Added",
  notMemberYet: 'Not a member yet?',
  description: 'Description',
  role: 'Roles',
  bug: "Bug",
  newTask: "New task",
  research: "Research",
  management: "Management",
  title: 'Title',
  enterName: "Enter Name",
  enterEmail: "Enter Email",
  enterMobileNumber: "Enter Mobile Number",
  enterCompanyName: "Enter Company Name",
  enterConfirmPassword: "Enter Confirm Password",
  addWebsite: "Add Website",
  enterPhoneNumber: "Enter Phone Number",
  addSkyId: "Add Skype ID",
  addLinkedInUrl: "Add LinkedIn URL",
  selectAModeOfContact: "Select a Mode of Contact",
  enterAddedDate: "Enter Added Date",
  enterLastUpdatedDate: "Enter Last Updated Date",
  readyToStart: "Ready To Start",
  inProgress: "In Progress",
  readyToQA: "Ready To QA",
  enterAddress: "Enter Address",
  selectAcountry: "Select a Country",
  enterState: "Enter State",
  enterCity: "Enter City",
  enterPostalCode: "Enter Postal Code",
  enterComments: "Enter Comments",
  enterCountry: "Enter Country",
  enterArea: "Enter Area",
  view: 'View',
  verifyOnCalendar:'Verify On Calendar',
  administrator: 'Administrator',
  policy: 'Policies',
  addUser: 'Add New User',
  bestForBusinessOwnersAndCompanyAdministrators:
    ' Best for business owners and company,administrators,',
  analystLabel:
    "Best for people who need full access to analytics data, but don't need to update business settings",
  editUser: 'Edit User',
  liveSiteURL: 'Live Site URL',
  searchPolicy: 'Search Policy',
  liveSiteCredential: 'Live Site Credential',
  analyst: 'Analyst',
  support: 'Support',
  noMatchFound: 'No matching records found',
  trial: 'Trial',
  developerLabel: 'Best for developers or people primarily using the API',
  trialLabel:
    " Best for people who need to preview content data, but don't need to make any updates",
  supportLabel: 'Best for employees who regularly refund payments and respond to disputes',
  developer: 'Developer',
  updatePolicy: 'Update policy',
  emailName: 'Email/Name',
  logo: 'Logo',
  selected: 'Selected',
  continue: 'Continue',
  filterOptions: 'Filter options',
  deleteSelected: 'Delete selected',
  addressContact: 'Address/Contact',
  salaryInformation: 'Salary Information',
  informed: "Informed",
  uninformed:'Uninformed',
  sickLeave:'Sick Leave',
  parentsHusbandGuardian: 'Parents / Husband / Guardian',
  low: 'Low',
  medium: "Medium",
  high: "High",
  parentsHusbandGuardianOne: 'Parents / Husband / Guardian 1',
  parentsHusbandGuardianTwo: 'Parents / Husband / Guardian 2',
  addressContactInformation: 'Address / Contact Information',
  nextIncrementMonth: 'Next Increment Month',
  incomeTaxNumber: 'PAN number',
  bank_details: 'Bank details',
  extraInformation: 'Extra information',
  pagesSize: "Page Size",
  avatar: 'Avatar',
  paidLeaveStartForm: 'Paid leave start form',
  paidLeave:'Paid Leave',
  slackUrl: 'Slack URL',
  aadhaarCardNumber: 'Aadhaar card number',
  backToPolicyList: 'Back to policy list',
  minutes: "Minutes",
  dateOfJoining: 'Date of joining',
  firstName: 'First name',
  lastName: 'Last name',
  officialWorkingDays: 'Official Working Days',
  birthDate: 'Birth date',
  mins: "Minutes",
  designation: 'Designation',
  leadView: "Lead View",
  contactEmail: 'Contact email',
  lead: 'Leads',
  leads: 'Leads',
  addLead: 'Add New Lead',
  enterEstimatedTimeInMinutes: 'Enter estimated time in minutes',
  editLead: 'Edit Lead',
  reset: 'Reset',
  submitWorkStatus:'Submit Work Status',
  roleNameShouldNotContainSpace: 'Role name should not contain space',
  updateLead: 'Update Lead',
  address: 'Address',
  area: 'Area',
  state: 'State',
  city: 'City',
  postalCode: 'Postal Code',
  mobileNumber: 'Mobile Number',
  alternativeMobileNumber: 'Alternative mobile number',
  name: 'Name',
  noString: '',
  contactNumber: 'Contact Number',
  updateUser: 'Update user',
  actions: 'Actions',
  pleaseSelectLastContactDate: 'Please select last contact date',
  pleaseEnterValidContactEmail: "Please enter valid contact email",
  edit: 'Edit',
  delete: 'Delete',
  noParentTaskFounded: "No parent task found",
  editPolicy: 'Edit policy',
  editRole: 'Edit Role',
  editCredentials: 'Edit credential',
  addRole: 'Add New Role',
  updateRole: 'Update Role',
  updateCredential: 'Update Credential',
  industries: 'Industries',
  technologies: 'Technologies',
  roleName: 'Role Name',
  updatePermission: 'Update Permission',
  addPermission: 'Add New Permission',
  roleList: 'Roles list',
  roleListing: 'Role Listing',
  credentialListing: 'Credentials',
  policyListing: 'Policy Listing',
  permissionList: 'Permissions list',
  permissionListing: 'Permission Listing',
  policyList: 'Policy List',
  userList: 'Users list',
  guardian: "Guardian",
  leadListing: 'Lead Listing',
  parentName: 'Parent Name',
  addPolicy: 'Add New Policy',
  qa: 'QA',
  policies: 'policies',
  history: 'History',
  roles: 'Roles',
  permissions: 'Permissions',
  editPermission: 'Edit Permission',
  permissionsList: 'Permissions list',
  attendance: 'Attendance',
  Calendar:'Calendar',
  filter: 'Filter',
  leaveDetails: 'Leave Details',
  export: 'Export',
  permissionName: 'Permission Name',
  searchUser: 'Search user',
  searchRole: 'Search role',
  searchCredentials: 'Search Credentials',
  selectType: "Select Type",
  selectAssignTo: "Select assign to",
  searchPermission: 'Search Permission',
  searchTask: 'Search task',
  clickOnBelowButtonToCreate: "Click On Below button to create",
  aNewTask: "a new task",
  pleaseEnterProfileUrl: 'Please select profile picture',
  pleaseSelectJoiningDate: 'Please select joining date',
  taskDetailsNotFound: 'Task details not found',
  taskEntry: 'Task Entry',
  masterList: 'Master List',
  pleaseEnterUserName: 'Please enter username',
  pleaseEnterFirstName: 'Please enter first name',
  pleaseEnterLastName: 'Please enter last name',
  pleaseEnterParentTask: "Please select parent task",
  pleaseSelectPriority: "Please select priority",
  pleaseSelectTaskType: "Please select task type",
  pleaseSelectBirthDate: 'Please select birth date',
  pleaseSelectAssignTo: 'Please select assign to',
  pleaseSelectQA: 'Please select QA',
  pleaseEnterDesignation: 'Please enter designation',
  pleaseEnterContactEmail: 'Please enter contact email',
  pleaseEnterAddress: 'Please enter address',
  pleaseEnterArea: 'Please enter area',
  pleaseSelectState: 'Please select a state',
  pleaseEnterCity: 'Please enter city',
  pleaseEnterPostalCode: 'Please enter postal code',
  pleaseEnterMobileNumber: 'Please enter mobile number',
  pleaseEnterMobile: 'Please enter mobile',
  mobileShouldBeTwelveDigit: 'Mobile should be 12 digit',
  mobileShouldBeTenDigit: 'Mobile at least 10 digit',
  mobileShouldBeNumber: 'Mobile number should be number',
  pleaseEnterAltMobile: 'Please enter alternative mobile number',
  pleaseEnterName: 'Please enter name',
  pleaseEnterDetils: 'Please enter Details',
  pleaseSelectTags: 'Please select tags',
  pleaseEnterPhone: 'Please enter phone',
  pleaseSelectColor: 'Please select color',
  pleaseEnterFtpDetails: 'Please enter ftp details',
  pleaseEnterDemoSite: 'Please enter demo site URL',
  pleaseEnterDemoSiteCredentials: 'Please enter demo site credentials',
  pleaseEnterLiveSiteUrl: 'Please enter live site URL',
  pleaseSelectLogo: 'Please select logo',
  pleaseEnterLiveSiteCredentials: 'Please enter live site credentials',
  pleaseSelectAttachment: 'Please select attachment',
  parent: "Parent",
  projectType: 'Project Type',
  iAgreeTo: 'I agree to',
  pleaseSelectIndustries: 'Please select industries',
  pleaseSelectTechnologies: 'Please select technologies',
  pleaseSelectProjectType: 'Please select project type',
  selectProject: 'Select Project',
  pleaseEnterGuardianPersonName: 'Please enter name',
  pleaseEnterGuardianPersonAddress: 'Please enter address',
  pleaseEnterGuardianPersonContactNumber: 'Please enter contact number',
  pleaseSelectNextIncrementMonth: 'Please select next increment month date',
  pleaseEnterPanNumber: 'Please enter PAN number',
  pleaseEnterBankDetails: 'Please enter bank details',
  pleaseEnterPermissionName: 'Please enter permission name',
  pleaseEnterRoleName: 'Please enter role name',
  pleaseEnterTitle: 'Please enter title',
  pleaseEnterDescription: 'Please enter description',
  pleaseEnterStatus:'Please Enter Status',
  module: 'Module',
  pleaseSelectStatus: 'Please select status',
  userWithEmailDoNotExists: 'User with email do not exists',
  pleaseEnterSalary: 'Please enter salary',
  pleaseEnterSlackUserName: 'Please enter slack user name',
  pleaseEnterSlackUserNumber: 'Please enter slack user number',
  pendingBy: "Pending By",
  pendingDate: "Pending Date",
  pleaseEnterPaidLeaveStartDate: 'Please select paid leave start date',
  pleaseEnterActualPrice: 'Please enter actual price',
  pleaseSelectOfficeValidTime: 'Please select office valid time',
  actualPriceShouldBeNumber: 'Actual price should be number',
  pleaseEnterSlackUrl: 'Please enter slack url',
  pleaseEnterReason: 'Please enter reason',
  pleaseEnterValidPercentage: "Please enter valid percentage",
  pleaseEnterAdharCardNumber: 'Please enter aadhaar card number',
  yourAccountNotVerified: 'Your account not activated',
  pleaseEnterEstimatedTime: "Please enter estimated time in minutes",
  pleaseEnterPercentage: 'Please enter percentage',
  credentialsIncorrect: 'Please enter valid Email or Password',
  leadDetailsNotFound: 'Lead details not found',
  slackUserName: 'Slack user name',
  slackUserNumber: 'Slack user number',
  loginLinkHasBeenSentToSlack: 'Login link has been sent to slack.',
  pleaseEnterValidEmail: 'Please enter valid email',
  yourAccountNotActivated: 'Your account not activate',
  userEmailDoNotExists: 'User with email do not exists. Please enter valid email.',
  lastContactDate: 'Last Contact Date',
  whyLeadIsCancelledWithReason: "Why lead is cancelled with reason",
  rejectedDate: 'Rejected Date',
  rejectedBy: "Rejected by",
  tags: 'Tags',
  youCanStopOnlyYourTask: "You can stop only your task",
  salaryShouldBeMaximumEightDigit: 'Salary should be maximum 8 digit',
  userDetailsDoesNotFound: 'User details does not found',
  userDetails: 'User details',
  search: 'Search',
  viewProfile: 'View Profile',
  project: 'Project',
  archive:'Archived Projects',
  projectListing: 'Project Listing',
  archiveListing:'Archive Listing',
  taskListing: "Task Listing",
  userListing: 'User Listing',
  user: 'User',
  tools: 'Tools',
  update: 'Update',
  updateProject: 'Update Project',
  updateTask: 'Update Task',
  technology: 'Select Technology',
  industry: 'Select Industry',
  panCardMustBeTenDigit: 'PAN Card number must be 10 digits',
  yourSocialCampaigns: 'Your Social Campaigns',
  crafted: 'Crafted',
  pages: 'Pages',
  profile: 'Profile',
  overview: 'Overview',
  campaigns: 'Campaigns',
  documents: 'Documents',
  connections: 'Connections',
  wizards: 'Wizards',
  vertical: 'Vertical',
  accounts: 'Accounts',
  secondary: 'Secondary',
  primary: 'Primary',
  horizontal: 'Horizontal',
  settings: 'Settings',
  errors: 'Errors',
  widgets: 'Widgets',
  chat: 'Chat',
  privateChat: 'Private Chat',
  groupChart: 'Group Chart',
  drawerChart: 'Drawer Chart',
  masterLeaves: "Admin Leaves List",
  userManagement: 'User management',
  megaMenu: 'Mega menu',
  leave: 'Leaves',
  leaveList: 'Leave List',
  master: 'Master',
  myLeaves: 'My Leaves List',
  leaves:"Leaves",
  addLeave: 'Add New Leave ',
  userLeave: 'Admin Leaves Calendar',
  percentage: "Percentage",
  taskType: "Task Type",
  taskStatus: "Task Status",
  leaveStartDate: 'start Date',
  leaveEndDate: 'End Date',
  leaveAddedDate: 'Leave Added Date',
  stopTask: 'Stop Task',
  startTask: 'Start Task',
  actualLeaveDateRange: 'Start Date - End Date',
  employee: 'Employee',
  leaveStatus: 'Leave Status',
  masterLeaveList: 'Master Leave List',
  editLeave: 'Edit Leave',
  updateLeave: 'Update Leave',
  pleaseEnterStartDate: 'please select start date',
  pleaseEnterEndDate: 'please select end date',
  pleaseSelectTaskStatus: "Please select task status",
  pleaseEnterValidEstimatedTime: "Please enter valid estimated time",
  pleaseEnterJoiningDate: 'Please select joining date',
  leaveIsSuccessfullyUpdate: 'Leave Is Successfully Update',
  leaveAddedSuccessfully: 'Leave Added Successfully',
  leaveExists: 'leave Exists',
  joiningDate: 'Joining Date',
  leaveDetailsNotFound: "Leave Details Not Found",
  usersDirectory: "usersDirectory",
  viewHistory: "View History",
  rejected: 'Rejected',
  select: "Select",
  your: 'your',
  viewLeave: "View Leave",
  updateDetails: "Update Details",
  enterYourReason: 'Enter Your Reason',
  task: "Task",
  taskName:"Task Name",
  updatedBy: "Updated By",
  deletedBy: "Deleted By",
  permissionsPathKey: "permission",
  youCanAccessYourTask: "You can track only your tasks",
  policyPathKey: "policy",
  leadPathKey: "lead",
  clientPathKey: "client",
  projectPathKey: "project",
  taskPathKey: "task",
  attendancePathKey: "attendance",
  noTasksFound: "No Tasks found.",
  ipPathKey: "ip",
  rolePathKey: "role",
  profilePathKey: "profile",
  waitingToStart: "Waiting To Start",
  inProcess: "In Process",
  onHold: "On Hold",
  taskView: "Task View",
  completedFromOurSide: "Completed From Our Side",
  completed: "Completed",
  changesOnLiveSite: "Changes On Live Site",
  html: "HTML",
  taskStatusSuccessfullyChanged: "Task Status Successfully Changed",
  taskSuccessfullyAssign: "Task Successfully assigned",
  pleaseSelectAnyTask: "Please Select any Task",
  parentTask: "Parent Task",
  css: "CSS",
  php: "PHP",
  PHP:"PHP",
  javaScript: "JavaScript",
  jQuery: "JQuery",
  react: "React",
  reactNative: "React Native",
  codeIgniter: "Code Igniter",
  laravel: "Laravel",
  wordPress: "WordPress",
  wooCommerce: "Woo Commerce",
  shopify: "Shopify",
  magento: "Magento",
  android: "Android",
  ios: "IOS",
  nodeJs: "Node.js",
  angularJs: "Angular.js",
  progress: "PROGRESS",
  reactJs: "React.js",
  yii: "YII",
  cakePhp: "Cake PHP",
  scss: "SCSS",
  wpBakeryVisualComposer: "WPBakery Visual Composer",
  elementor: "Elementor",
  wordPressSalientTheme: "WordPress - Salient Theme",
  wordPressWPBakeryPageBuilder: "WordPress - WPBakery Page Builder",
  save: "Save",
  normal: "Normal",
    newLead:"New Lead",
    needToReplyToOldLead:"Need to reply to old lead",
    repliedToClient:"Replied to client",
    clientMeetingFixed:"Client Meeting fixed",
    clientMeetingDone:"Client Meeting done",
    leadAssessmentTest:"Lead Assessment Test",
    quotePending:"Quote Pending",
    futureLead:"Future Lead",
    quoteProvided:"Quote Provided",
    waitingForSirReply:"Waiting for Sir's Reply",
    replayBack:"Replay back",
    followUp:"Follow Up",
    leadCancelled:"Lead Cancelled",
    waitingForTheClientRepl:"Waiting for the client reply",
    backlog: "Backlog",
    readyForWork: "Ready For Work",
    inWorking: "In Working",
    readyToQa: "Ready To QA",
}
