const api = {
  auth: {
    register: '/auth/register',
    login: '/auth/login',
    otp: '/auth/sendOtp',
    logout: '/auth/logout',
    forgotPassword: '/auth/forgotPassword',
    resetPassword: '/auth/resetPassword',
    verifyToken: '/auth/verifyToken',
    activateAccount: 'auth/activateUserAccount',
    profile: '/auth/userDetails',
  },
  dashboard: {
    recentTasks: '/user/userRecentTasks',
    upcomingBirthday: '/user/upcomingBirthdays',
    upcomingWorkAnniversary: '/user/upcomingWorkAnniversary',
    todayOnLeave: '/user/todayOnLeave',
    allOnlineUser: '/user/allOnlineUsers',
    lastOfflineUsers: '/user/lastOfflineUsers',
  },
  roles: {
    list: '/role',
  },
  credentials: {
    list: '/credentials',
    add: '/credentials/add',
    edit: '/credentials/update',
    individual: '/credentials/show',
  },
  permissions: {
    list: '/permission',
  },
  users: {
    list: '/user',
    add: '/user/add',
    individual: '/user/show',
    update: '/user/update',
  },
  attendance: {
    calendarList: '/user/userAttendanceCalendar',
    masterAttendanceList: 'user/masterAttendanceList',
    holiday: {
      list: '/holiday',
      add: '/holiday/add',
      deleteMultiple: '/holiday/deleteMholiday',
      edit: 'holiday/update',
      view: 'holiday/show/',
    },
  },
  policy: {
    list: '/policy',
    read: '/policy/read',
    unread: '/user/unread-policy/list',
  },
  history: {
    log: '/policylog',
  },
  userPermissions: {
    list: '/user/permission',
  },
  lead: {
    list: '/lead',
    add: '/lead/add',
    individual: '/lead/show',
    update: '/lead/update',
  },
  client: {
    list: '/client',
    individual: '/client/show',
    update: '/client/update',
  },
  project: {
    list: '/project',
    add: '/project/add',
    update: '/project/update',
    individual: '/project/show',
    parentTask: '/project/maintasks',
    portfolio: '/project/portfolio',
  },
  userProjects: {
    list: '/user/project',
  }, 
  task: {
    list: '/task',
    add: '/task/add',
    assignMultiple: '/task/assignMultiple',
    multiPleTaskStatus: '/task/changeStatus',
    deleteMCorrectionRequests: '/task_correction_requests/deleteMCorrectionRequests',
    deleteMultiple: '/task/deleteMultiple',
    individual: 'task/show',
    track: '/task/startStop',
    update: '/task/update',
    updateCheckList: '/task/checklistupdate',
    addCheckList: '/checklist/add',
    deleteCheckList: '/checklist/deleteChecklist',
    editCheckListItem: 'checklist/update',
    singleDayEntry: '/task/singleDayTasks',
    dailyTaskSlackNotification: '/task/dailyTaskSlackNotification',
    taskCorrectionRequest: '/task_correction_requests',
    addTaskCorrectionRequest: 'task_correction_requests/add',
    taskCorrectionList: '/task_correction_requests',
    updateTaskCorrectionList: '/task_correction_requests/update',
    updateTaskCorrectionStatus: '/task_correction_requests/statusUpdate',
    taskCorrectionStatusUpdate: '/task_correction_requests/statusUpdate',
  },
  module: {
    list: '/module',
  },
  ip: {
    list: '/ip',
    add: '/ip/add',
    update: 'ip/update',
    individual: '/ip/show',
    validate: 'ip/validate',
  },
  leave: {
    list: '/leave',
    add: '/leave/add',
    update: '/leave/update',
    userLeave: '/user/leave/list',
    individual: '/leave/show',
    calendar: '/user/userLeaveCalendar',
    validate: '/leave/validate',
  },
}

export default api
